docs: steps to integrate telegraf into kepler
sustainable-computing-io/kepler-doc pull request #139
Opened 2024-03-15 11:41 UTC by Shobhij

2024-03-27 14:53 UTC, rootfs commented
@Shobhij can you sign the DCO?
```
Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
In your local branch, run: git rebase HEAD~4 --signoff
Force push your changes to overwrite the branch: git push --force-with-lease origin main
```

2024-04-02 11:43 UTC, maryamtahhan requested changes
Sorry about all the comments - these are mostly markdown linter changes. 
I've proposed adding the linter to the PR workflows and this PR will fail if it's run through the linter.

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +```
add a new line after the code block

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +```
```suggestion

```bash
```

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +
```suggestion
```

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +```
add a new line after the code block

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +```
add a new line after the code block

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +Below is the sample config that have been used to enable all the
```suggestion
Below is the sample config that was used to enable all the
```

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +above-mentioned plugins. Although, user can enable any other desired
```suggestion
above-mentioned plugins. Although, the user can enable any other desired
```

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +```
```suggestion
```bash
```

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +```
add a new line after the code block

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +```
```suggestion

```bash
```

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +Download and start the Prometheus container
fixup this top level title to be a level 2 or 3 header

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +Prometheus can be installed on a system in various ways. Here it is
```suggestion
Prometheus can be installed on a system in various ways. Here it is simply run inside a container.
```

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +```
```suggestion

```bash
```

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +```
Add a new line after a code block

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +```
```suggestion

```bash
```

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +```
Add a new line after a code block

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +![](../fig/Kepler-Telegraf-Prometheus.png)
Needs an image name to pass the markdown linter

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +Download and start Grafana container
Fixup title level

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +```
```suggestion

```bash
```

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +```
Add a new line after a code block

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +Once Grafana container is running access the Grafana GUI at localhost:3000. Login with default credentials. After login, The Prometheus database needs to be added as a data source into Grafana GUI. C
```suggestion
Once the Grafana container is running, access the Grafana GUI at localhost:3000. Login with the default credentials. After login, the Prometheus database needs to be added as a data source into the Grafana GUI. Click on `DATA SOURCES` -> `Add your first data source`
```

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +And select Prometheus - > Click “Save and Test”
```suggestion
and select Prometheus - > Click “Save and Test”
```

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +And select Prometheus - > Click “Save and Test”
should probably add this to the line above it

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +Dashboard
fixup title level

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +For example in below shown example, right hand shows Power related
```suggestion
For example in the image below, the right hand panel shows power related
```

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +metrics collected by Telegraf whereas left hand shows Power related
```suggestion
metrics collected by Telegraf whereas left hand panel shows power related
```

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +![](../fig/Kepler-Telegraf-dashboard.png)
image needs a title

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +
Too many new lines

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +**On Kepler side:**
would fix this as a lower level header with `####`

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +**On Telegraf side:**
would fix this as a lower level header with ####

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +
Maybe create a bullet list for the items below

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +
Also maybe a bullet list for the items below would make it a little more readable.

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +**PKG-\>** Represents kepler\_container\_package\_joules\_total metrics
```suggestion
**PKG-\>** Represents `kepler_container_package_joules_total metrics`
```

You don't need to escape underscores in MD

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +**PKG-\>** Represents kepler\_container\_package\_joules\_total metrics
same comment goes for all the escaped underscores that follow

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +consumption (from acpi) less the RAPL Package and DRAM.
```suggestion
consumption (from ACPI) less the RAPL Package and DRAM.
```

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +Telegraf- IPMI metric
```suggestion
Telegraf-IPMI metric
```

Also fixup header level with the appropriate number of `##`

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +Supply Current out %.
```suggestion
supply current out percentage.
```

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +On Kepler dashboard, we are also pulling IPMI metrics which show Power
```suggestion
On Kepler dashboard, we are also pulling IPMI metrics which show power
```

2024-04-02 11:43 UTC, maryamtahhan commented on docs/installation/Kepler-Telegraf-integration-steps.md
> +![](../fig/Kepler-Telegraf-IPMI.png)
figure needs a name for the MD linter

2024-04-02 15:02 UTC, Shobhij commented
> @Shobhij can you sign the DCO?
> 
> ```
> Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
> In your local branch, run: git rebase HEAD~4 --signoff
> Force push your changes to overwrite the branch: git push --force-with-lease origin main
> ```

Done!!

2024-04-03 10:21 UTC, Shobhij commented
> @Shobhij can you sign the DCO?
> 
> ```
> Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
> In your local branch, run: git rebase HEAD~4 --signoff
> Force push your changes to overwrite the branch: git push --force-with-lease origin main
> ```

Done!!

2024-04-03 12:24 UTC, Shobhij commented
Looks like by mistake my git rebase HEAD~41 -sign off command, signed off last 41 commits. Can anyone suggest how can I fix this? I was trying to signoff the commits on my pull request and by mistake did HEAD~41..

2024-04-03 12:43 UTC, closed without merging